package com.henu.reservoir.dao;

import com.henu.reservoir.domain.CalModelDao;

public interface CalModelDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(CalModelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(CalModelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    CalModelDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(CalModelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(CalModelDao record);
}