package com.henu.reservoir.dao;

import com.henu.reservoir.domain.CutAlgoDao;

import java.util.List;

public interface CutAlgoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(CutAlgoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(CutAlgoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    CutAlgoDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(CutAlgoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cut_algo
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(CutAlgoDao record);

    //选择所有分割算法
    List<CutAlgoDao> selectAll();
}