package com.henu.reservoir.dao;

import com.henu.reservoir.domain.MeasuredLevelDao;

public interface MeasuredLevelDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insert(MeasuredLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insertSelective(MeasuredLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    MeasuredLevelDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKeySelective(MeasuredLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKey(MeasuredLevelDao record);
}