package com.henu.reservoir.dao;

import com.henu.reservoir.domain.MeasuredResultDao;

public interface MeasuredResultDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insert(MeasuredResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insertSelective(MeasuredResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    MeasuredResultDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKeySelective(MeasuredResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKey(MeasuredResultDao record);
}