package com.henu.reservoir.dao;

import com.henu.reservoir.domain.OpticalImgDao;

public interface OpticalImgDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int insert(OpticalImgDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int insertSelective(OpticalImgDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    OpticalImgDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int updateByPrimaryKeySelective(OpticalImgDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int updateByPrimaryKey(OpticalImgDao record);
}