package com.henu.reservoir.dao;

import com.henu.reservoir.domain.RadarResultDao;

public interface RadarResultDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insert(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insertSelective(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    RadarResultDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKeySelective(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKey(RadarResultDao record);
}