package com.henu.reservoir.dao;

import com.henu.reservoir.domain.RadarResultDao;

import java.util.List;

public interface RadarResultDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    RadarResultDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(RadarResultDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(RadarResultDao record);

    //通过水库id查找RadarResult
    List<RadarResultDao> selectByReservoirId(Integer id);

    //使用reservoir_id和date获取1
    RadarResultDao selectByReservoirIdAndDate(RadarResultDao record);

    //使用reservoir_id和date更新1
    int updateByReservoirIdAndDate(RadarResultDao record);

    //选出当前年份所有的遥测水位数据
    List<RadarResultDao> selectCurrentYear();
}