package com.henu.reservoir.dao;

import com.henu.reservoir.domain.RadarLevelDao;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

public interface RadarLevelDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(RadarLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(RadarLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    RadarLevelDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(RadarLevelDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(RadarLevelDao record);

    //根据日期和卫星名查找雷达高度计
    RadarLevelDao selectByDateAndSatelliteNameAndReservoirId(
            @Param("date") Date date,
            @Param("satelliteName") String satelliteName,
            @Param("reservoirId") Integer reservoirId
    );
}