package com.henu.reservoir.dao;

import com.henu.reservoir.domain.ReservoirInfoDao;

public interface ReservoirInfoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int insert(ReservoirInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int insertSelective(ReservoirInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    ReservoirInfoDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int updateByPrimaryKeySelective(ReservoirInfoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    int updateByPrimaryKey(ReservoirInfoDao record);
}