package com.henu.reservoir.dao;

import com.henu.reservoir.domain.WaterStorageDao;

public interface WaterStorageDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insert(WaterStorageDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int insertSelective(WaterStorageDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    WaterStorageDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKeySelective(WaterStorageDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_storage
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    int updateByPrimaryKey(WaterStorageDao record);
}