package com.henu.reservoir.dao;

import com.henu.reservoir.domain.RadarResultDao;
import com.henu.reservoir.domain.WaterAreaDao;

import java.util.List;

public interface WaterAreaDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    WaterAreaDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(WaterAreaDao record);

    //通过水库id查找所有WaterAreaDao
    List<WaterAreaDao> selectByReservoirId(Integer id);

    List<WaterAreaDao> selectAll();

    //通过水库id查找Sar的WaterAreaDao
    List<WaterAreaDao> selectSarByReservoirId(Integer id);

    //通过水库id查找光学的WaterAreaDao
    List<WaterAreaDao> selectOpticalByReservoirId(Integer id);

    //查找sar或光学影像今年的面积数据
    List<WaterAreaDao> selectCurrentYear(Integer isSAR);
}