package com.henu.reservoir.dao;

import com.henu.reservoir.domain.WaterAreaDao;

public interface WaterAreaDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insert(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int insertSelective(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    WaterAreaDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(WaterAreaDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    int updateByPrimaryKey(WaterAreaDao record);
}