server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  # 数据源配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservoir?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    name: reservoir
  profiles:
    active: dev
  application:
    name: reservoir
  thymeleaf:
    cache: false
    suffix: .html
    enabled: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    mode: HTML
  servlet:
    multipart:
      max-file-size: "2048MB"
      max-request-size: "2048MB"
  mvc:
    static-path-pattern: /static/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: jdbc

mybatis:
  type-aliases-package: com.henu.reservoir.domain
  mapper-locations: classpath:mapper/*.xml
