package com.henu.reservoir.domain;

public class CalModelDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_model.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cal_model.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer reservoirId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public CalModelDao(Integer id, Integer reservoirId) {
        this.id = id;
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cal_model
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public CalModelDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_model.id
     *
     * @return the value of cal_model.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_model.id
     *
     * @param id the value for cal_model.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cal_model.reservoir_id
     *
     * @return the value of cal_model.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cal_model.reservoir_id
     *
     * @param reservoirId the value for cal_model.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }
}