package com.henu.reservoir.domain;

public class MeasuredResultDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_result.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_result.measured_level_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer measuredLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_result.water_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String waterLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_result.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer reservoirId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public MeasuredResultDao(Integer id, Integer measuredLevelId, String waterLevel, Integer reservoirId) {
        this.id = id;
        this.measuredLevelId = measuredLevelId;
        this.waterLevel = waterLevel;
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_result
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public MeasuredResultDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_result.id
     *
     * @return the value of measured_result.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_result.id
     *
     * @param id the value for measured_result.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_result.measured_level_id
     *
     * @return the value of measured_result.measured_level_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getMeasuredLevelId() {
        return measuredLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_result.measured_level_id
     *
     * @param measuredLevelId the value for measured_result.measured_level_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setMeasuredLevelId(Integer measuredLevelId) {
        this.measuredLevelId = measuredLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_result.water_level
     *
     * @return the value of measured_result.water_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getWaterLevel() {
        return waterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_result.water_level
     *
     * @param waterLevel the value for measured_result.water_level
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setWaterLevel(String waterLevel) {
        this.waterLevel = waterLevel == null ? null : waterLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_result.reservoir_id
     *
     * @return the value of measured_result.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_result.reservoir_id
     *
     * @param reservoirId the value for measured_result.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }
}