package com.henu.reservoir.domain;

import java.util.Date;

public class MeasuredLevelDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_level.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_level.site_name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_level.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer reservoirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_level.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measured_level.path
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public MeasuredLevelDao(Integer id, String siteName, Integer reservoirId, Date date, String path) {
        this.id = id;
        this.siteName = siteName;
        this.reservoirId = reservoirId;
        this.date = date;
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measured_level
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public MeasuredLevelDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_level.id
     *
     * @return the value of measured_level.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_level.id
     *
     * @param id the value for measured_level.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_level.site_name
     *
     * @return the value of measured_level.site_name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_level.site_name
     *
     * @param siteName the value for measured_level.site_name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_level.reservoir_id
     *
     * @return the value of measured_level.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_level.reservoir_id
     *
     * @param reservoirId the value for measured_level.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_level.date
     *
     * @return the value of measured_level.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_level.date
     *
     * @param date the value for measured_level.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measured_level.path
     *
     * @return the value of measured_level.path
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measured_level.path
     *
     * @param path the value for measured_level.path
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}