package com.henu.reservoir.domain;

import java.util.Date;

public class OpticalImgDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer reservoirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.satellite_name
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String satelliteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.date
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String toplLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String toprLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String lowerlLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String lowerrLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String toplLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String toprLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String lowerlLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String lowerrLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.cycle
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private Integer cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.path
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public OpticalImgDao(Integer id, Integer reservoirId, String satelliteName, Date date, String toplLongitude, String toprLongitude, String lowerlLongitude, String lowerrLongitude, String toplLatitude, String toprLatitude, String lowerlLatitude, String lowerrLatitude, Integer cycle, String path) {
        this.id = id;
        this.reservoirId = reservoirId;
        this.satelliteName = satelliteName;
        this.date = date;
        this.toplLongitude = toplLongitude;
        this.toprLongitude = toprLongitude;
        this.lowerlLongitude = lowerlLongitude;
        this.lowerrLongitude = lowerrLongitude;
        this.toplLatitude = toplLatitude;
        this.toprLatitude = toprLatitude;
        this.lowerlLatitude = lowerlLatitude;
        this.lowerrLatitude = lowerrLatitude;
        this.cycle = cycle;
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public OpticalImgDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.id
     *
     * @return the value of optical_img.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.id
     *
     * @param id the value for optical_img.id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.reservoir_id
     *
     * @return the value of optical_img.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.reservoir_id
     *
     * @param reservoirId the value for optical_img.reservoir_id
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.satellite_name
     *
     * @return the value of optical_img.satellite_name
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getSatelliteName() {
        return satelliteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.satellite_name
     *
     * @param satelliteName the value for optical_img.satellite_name
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setSatelliteName(String satelliteName) {
        this.satelliteName = satelliteName == null ? null : satelliteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.date
     *
     * @return the value of optical_img.date
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.date
     *
     * @param date the value for optical_img.date
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topL_longitude
     *
     * @return the value of optical_img.topL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getToplLongitude() {
        return toplLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topL_longitude
     *
     * @param toplLongitude the value for optical_img.topL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setToplLongitude(String toplLongitude) {
        this.toplLongitude = toplLongitude == null ? null : toplLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topR_longitude
     *
     * @return the value of optical_img.topR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getToprLongitude() {
        return toprLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topR_longitude
     *
     * @param toprLongitude the value for optical_img.topR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setToprLongitude(String toprLongitude) {
        this.toprLongitude = toprLongitude == null ? null : toprLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerL_longitude
     *
     * @return the value of optical_img.lowerL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getLowerlLongitude() {
        return lowerlLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerL_longitude
     *
     * @param lowerlLongitude the value for optical_img.lowerL_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setLowerlLongitude(String lowerlLongitude) {
        this.lowerlLongitude = lowerlLongitude == null ? null : lowerlLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerR_longitude
     *
     * @return the value of optical_img.lowerR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getLowerrLongitude() {
        return lowerrLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerR_longitude
     *
     * @param lowerrLongitude the value for optical_img.lowerR_longitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setLowerrLongitude(String lowerrLongitude) {
        this.lowerrLongitude = lowerrLongitude == null ? null : lowerrLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topL_latitude
     *
     * @return the value of optical_img.topL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getToplLatitude() {
        return toplLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topL_latitude
     *
     * @param toplLatitude the value for optical_img.topL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setToplLatitude(String toplLatitude) {
        this.toplLatitude = toplLatitude == null ? null : toplLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topR_latitude
     *
     * @return the value of optical_img.topR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getToprLatitude() {
        return toprLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topR_latitude
     *
     * @param toprLatitude the value for optical_img.topR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setToprLatitude(String toprLatitude) {
        this.toprLatitude = toprLatitude == null ? null : toprLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerL_latitude
     *
     * @return the value of optical_img.lowerL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getLowerlLatitude() {
        return lowerlLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerL_latitude
     *
     * @param lowerlLatitude the value for optical_img.lowerL_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setLowerlLatitude(String lowerlLatitude) {
        this.lowerlLatitude = lowerlLatitude == null ? null : lowerlLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerR_latitude
     *
     * @return the value of optical_img.lowerR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getLowerrLatitude() {
        return lowerrLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerR_latitude
     *
     * @param lowerrLatitude the value for optical_img.lowerR_latitude
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setLowerrLatitude(String lowerrLatitude) {
        this.lowerrLatitude = lowerrLatitude == null ? null : lowerrLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.cycle
     *
     * @return the value of optical_img.cycle
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.cycle
     *
     * @param cycle the value for optical_img.cycle
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.path
     *
     * @return the value of optical_img.path
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.path
     *
     * @param path the value for optical_img.path
     *
     * @mbg.generated Mon Dec 30 10:43:32 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}