package com.henu.reservoir.domain;

import java.util.Date;

public class OpticalImgDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer reservoirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.satellite_name
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String satelliteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.cycle
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.path
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topL_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String toplLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerR_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String lowerrLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.topL_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String toplLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column optical_img.lowerR_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String lowerrLatitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public OpticalImgDao(Integer id, Integer reservoirId, String satelliteName, Date date, Integer cycle, String path, String toplLongitude, String lowerrLongitude, String toplLatitude, String lowerrLatitude) {
        this.id = id;
        this.reservoirId = reservoirId;
        this.satelliteName = satelliteName;
        this.date = date;
        this.cycle = cycle;
        this.path = path;
        this.toplLongitude = toplLongitude;
        this.lowerrLongitude = lowerrLongitude;
        this.toplLatitude = toplLatitude;
        this.lowerrLatitude = lowerrLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optical_img
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public OpticalImgDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.id
     *
     * @return the value of optical_img.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.id
     *
     * @param id the value for optical_img.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.reservoir_id
     *
     * @return the value of optical_img.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.reservoir_id
     *
     * @param reservoirId the value for optical_img.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.satellite_name
     *
     * @return the value of optical_img.satellite_name
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getSatelliteName() {
        return satelliteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.satellite_name
     *
     * @param satelliteName the value for optical_img.satellite_name
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setSatelliteName(String satelliteName) {
        this.satelliteName = satelliteName == null ? null : satelliteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.date
     *
     * @return the value of optical_img.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.date
     *
     * @param date the value for optical_img.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.cycle
     *
     * @return the value of optical_img.cycle
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.cycle
     *
     * @param cycle the value for optical_img.cycle
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.path
     *
     * @return the value of optical_img.path
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.path
     *
     * @param path the value for optical_img.path
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topL_longitude
     *
     * @return the value of optical_img.topL_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getToplLongitude() {
        return toplLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topL_longitude
     *
     * @param toplLongitude the value for optical_img.topL_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setToplLongitude(String toplLongitude) {
        this.toplLongitude = toplLongitude == null ? null : toplLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerR_longitude
     *
     * @return the value of optical_img.lowerR_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getLowerrLongitude() {
        return lowerrLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerR_longitude
     *
     * @param lowerrLongitude the value for optical_img.lowerR_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setLowerrLongitude(String lowerrLongitude) {
        this.lowerrLongitude = lowerrLongitude == null ? null : lowerrLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.topL_latitude
     *
     * @return the value of optical_img.topL_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getToplLatitude() {
        return toplLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.topL_latitude
     *
     * @param toplLatitude the value for optical_img.topL_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setToplLatitude(String toplLatitude) {
        this.toplLatitude = toplLatitude == null ? null : toplLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column optical_img.lowerR_latitude
     *
     * @return the value of optical_img.lowerR_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getLowerrLatitude() {
        return lowerrLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column optical_img.lowerR_latitude
     *
     * @param lowerrLatitude the value for optical_img.lowerR_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setLowerrLatitude(String lowerrLatitude) {
        this.lowerrLatitude = lowerrLatitude == null ? null : lowerrLatitude.trim();
    }
}