package com.henu.reservoir.domain;

import java.util.Date;

public class RadarResultDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.water_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String waterLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.radar_level_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer radarLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.site_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String siteLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.site_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private String siteLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radar_result.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    private Integer reservoirId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public RadarResultDao(Integer id, Date date, String waterLevel, Integer radarLevelId, String siteLongitude, String siteLatitude, Integer reservoirId) {
        this.id = id;
        this.date = date;
        this.waterLevel = waterLevel;
        this.radarLevelId = radarLevelId;
        this.siteLongitude = siteLongitude;
        this.siteLatitude = siteLatitude;
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radar_result
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public RadarResultDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.id
     *
     * @return the value of radar_result.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.id
     *
     * @param id the value for radar_result.id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.date
     *
     * @return the value of radar_result.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.date
     *
     * @param date the value for radar_result.date
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.water_level
     *
     * @return the value of radar_result.water_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getWaterLevel() {
        return waterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.water_level
     *
     * @param waterLevel the value for radar_result.water_level
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setWaterLevel(String waterLevel) {
        this.waterLevel = waterLevel == null ? null : waterLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.radar_level_id
     *
     * @return the value of radar_result.radar_level_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getRadarLevelId() {
        return radarLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.radar_level_id
     *
     * @param radarLevelId the value for radar_result.radar_level_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setRadarLevelId(Integer radarLevelId) {
        this.radarLevelId = radarLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.site_longitude
     *
     * @return the value of radar_result.site_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getSiteLongitude() {
        return siteLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.site_longitude
     *
     * @param siteLongitude the value for radar_result.site_longitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setSiteLongitude(String siteLongitude) {
        this.siteLongitude = siteLongitude == null ? null : siteLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.site_latitude
     *
     * @return the value of radar_result.site_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public String getSiteLatitude() {
        return siteLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.site_latitude
     *
     * @param siteLatitude the value for radar_result.site_latitude
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setSiteLatitude(String siteLatitude) {
        this.siteLatitude = siteLatitude == null ? null : siteLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radar_result.reservoir_id
     *
     * @return the value of radar_result.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radar_result.reservoir_id
     *
     * @param reservoirId the value for radar_result.reservoir_id
     *
     * @mbg.generated Tue Dec 31 10:42:04 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }
}