package com.henu.reservoir.domain;

public class ReservoirInfoDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.location
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.longitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String longitudeLeft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.longitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String longitudeRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.latitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String latitudeLeft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservoir_info.latitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String latitudeRight;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public ReservoirInfoDao(Integer id, String name, String location, String longitudeLeft, String longitudeRight, String latitudeLeft, String latitudeRight) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.longitudeLeft = longitudeLeft;
        this.longitudeRight = longitudeRight;
        this.latitudeLeft = latitudeLeft;
        this.latitudeRight = latitudeRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservoir_info
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public ReservoirInfoDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.id
     *
     * @return the value of reservoir_info.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.id
     *
     * @param id the value for reservoir_info.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.name
     *
     * @return the value of reservoir_info.name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.name
     *
     * @param name the value for reservoir_info.name
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.location
     *
     * @return the value of reservoir_info.location
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.location
     *
     * @param location the value for reservoir_info.location
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.longitude_left
     *
     * @return the value of reservoir_info.longitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getLongitudeLeft() {
        return longitudeLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.longitude_left
     *
     * @param longitudeLeft the value for reservoir_info.longitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setLongitudeLeft(String longitudeLeft) {
        this.longitudeLeft = longitudeLeft == null ? null : longitudeLeft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.longitude_right
     *
     * @return the value of reservoir_info.longitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getLongitudeRight() {
        return longitudeRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.longitude_right
     *
     * @param longitudeRight the value for reservoir_info.longitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setLongitudeRight(String longitudeRight) {
        this.longitudeRight = longitudeRight == null ? null : longitudeRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.latitude_left
     *
     * @return the value of reservoir_info.latitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getLatitudeLeft() {
        return latitudeLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.latitude_left
     *
     * @param latitudeLeft the value for reservoir_info.latitude_left
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setLatitudeLeft(String latitudeLeft) {
        this.latitudeLeft = latitudeLeft == null ? null : latitudeLeft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservoir_info.latitude_right
     *
     * @return the value of reservoir_info.latitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getLatitudeRight() {
        return latitudeRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservoir_info.latitude_right
     *
     * @param latitudeRight the value for reservoir_info.latitude_right
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setLatitudeRight(String latitudeRight) {
        this.latitudeRight = latitudeRight == null ? null : latitudeRight.trim();
    }
}