package com.henu.reservoir.domain;

import java.util.Date;

public class WaterAreaDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer reservoirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.img_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.algo_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Integer algoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column water_area.is_sar_area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    private Byte isSarArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public WaterAreaDao(Integer id, Integer reservoirId, String area, Integer imgId, Integer algoId, Date date, Byte isSarArea) {
        this.id = id;
        this.reservoirId = reservoirId;
        this.area = area;
        this.imgId = imgId;
        this.algoId = algoId;
        this.date = date;
        this.isSarArea = isSarArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table water_area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public WaterAreaDao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.id
     *
     * @return the value of water_area.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.id
     *
     * @param id the value for water_area.id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.reservoir_id
     *
     * @return the value of water_area.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getReservoirId() {
        return reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.reservoir_id
     *
     * @param reservoirId the value for water_area.reservoir_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setReservoirId(Integer reservoirId) {
        this.reservoirId = reservoirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.area
     *
     * @return the value of water_area.area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.area
     *
     * @param area the value for water_area.area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.img_id
     *
     * @return the value of water_area.img_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.img_id
     *
     * @param imgId the value for water_area.img_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.algo_id
     *
     * @return the value of water_area.algo_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Integer getAlgoId() {
        return algoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.algo_id
     *
     * @param algoId the value for water_area.algo_id
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setAlgoId(Integer algoId) {
        this.algoId = algoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.date
     *
     * @return the value of water_area.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.date
     *
     * @param date the value for water_area.date
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column water_area.is_sar_area
     *
     * @return the value of water_area.is_sar_area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public Byte getIsSarArea() {
        return isSarArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column water_area.is_sar_area
     *
     * @param isSarArea the value for water_area.is_sar_area
     *
     * @mbg.generated Mon Dec 30 16:17:32 CST 2019
     */
    public void setIsSarArea(Byte isSarArea) {
        this.isSarArea = isSarArea;
    }
}